DefaultContentLanguage = "en"
author = "Vicente"
baseURL = ""
copyright = "Copyright © 2020, CodyLearn; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 4
theme = "casper3"
title = "CodyLearn 🎓"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "categories"
name = "Categorías"
url = "/categories/"
weight = 20
[[menu.main]]
identifier = "discord"
name = "Discord"
url = "https://discord.gg/vrMFDUs"
weight = 30
[params]
description = "Aprende a programar"
facebook = "https://facebook.com"
github = "https://github.com/CodyLearn"
logo = "/images/logocodylearn.png"
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
